default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
mastodon-previous: styles/mastodon-previous.scss
slack-like-mastodon: styles/slack-like-mastodon.scss
